import { Trash, X } from "@phosphor-icons/react";
import { useEffect, useState } from "react";
const empty = { title: "", description: "", status: "pending", priority: "medium", dueDate: new Date().toISOString().slice(0, 10), category: "" };
export function TaskModal({ task, initialStatus, categories, onClose, onSave, onDelete }) {
  const [form, setForm] = useState(empty);
  useEffect(() => setForm(task ? { ...task, category: task.category._id, dueDate: task.dueDate.slice(0, 10) } : { ...empty, status: initialStatus || "pending", category: categories[0]?._id || "" }), [task, initialStatus, categories]);
  function submit(event) { event.preventDefault(); onSave({ ...form, _id: task?._id }); }
  return <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="task-modal-title"><header><div><p className="eyebrow">{task ? "Editar tarea" : "Nueva tarea"}</p><h2 id="task-modal-title">{task ? task.title : "Sumá un nuevo objetivo"}</h2></div><button className="icon-button" onClick={onClose} aria-label="Cerrar"><X size={22} /></button></header><form onSubmit={submit} className="modal-form"><label className="field field--wide"><span>Título</span><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required maxLength="120" /></label><label className="field field--wide"><span>Descripción</span><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} maxLength="800" /></label><label className="field"><span>Estado</span><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="pending">Pendiente</option><option value="in_progress">En progreso</option><option value="completed">Completada</option></select></label><label className="field"><span>Prioridad</span><select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option></select></label><label className="field"><span>Categoría</span><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} required>{categories.map((cat) => <option key={cat._id} value={cat._id}>{cat.name}</option>)}</select></label><label className="field"><span>Fecha límite</span><input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} required /></label><footer>{task && <button type="button" className="button button--danger" onClick={() => onDelete(task)}><Trash />Eliminar</button>}<span /><button type="button" className="button button--ghost" onClick={onClose}>Cancelar</button><button className="button button--primary">Guardar tarea</button></footer></form></section></div>;
}
